export const symptoms = [
    "Chills" ,
    "Sweating" ,
    "Shortness of Breath on Exertion" ,
    "Palpitations" ,
    "Loss of Balance" ,
    "Joint Swelling" ,
    "Joint Stiffness" ,
    "Skin Discoloration" ,
    "Confusion" ,
    "Memory Problems" ,
    "Difficulty Concentrating" ,
    "Mood Swings" ,
    "Hallucinations" ,
    "Seizures" ,
    "Tremors" ,
    "Weakness" ,
    "Blurred Vision" ,
    "Dry Eyes" ,
    "Chest Tightness" ,
    "Abdominal Bloating" ,
    "Constipation" ,
    "Diarrhea with Blood" ,
    "Blood in Stool" ,
    "Hemorrhoids" ,
    "Urinary Frequency" ,
    "Painful Urination" ,
    "Blood in Urine" ,
    "Frequent Nighttime Urination" ,
    "Changes in Taste or Smell" ,
    "Loss of Smell or Taste" ,
    "Fever" ,
    "Headache" ,
    "Cough" ,
    "Sore Throat" ,
    "Runny or Stuffy Nose" ,
    "Shortness of Breath" ,
    "Fatigue" ,
    "Nausea" ,
    "Vomiting" ,
    "Diarrhea" ,
    "Abdominal Pain" ,
    "Chest Pain" ,
    "Back Pain" ,
    "Joint Pain" ,
    "Muscle Pain" ,
    "Swelling" ,
    "Rash" ,
    "Itching" ,
    "Difficulty Swallowing" ,
    "Dizziness" ,
    "Fainting" ,
    "Vision Changes" ,
    "Hearing Loss" ,
    "Bleeding or Bruising" ,
    "Numbness or Tingling" ,
    "Urinary Problems" ,
    "Bowel Problems" ,
    "Weight Loss" ,
    "Weight Gain" ,
    "Loss of Appetite" 
  ];
  
// export const symptoms = [
//   { name: "Chills" },
//   { name: "Sweating" },
//   { name: "Shortness of Breath on Exertion" },
//   { name: "Palpitations" },
//   { name: "Loss of Balance" },
//   { name: "Joint Swelling" },
//   { name: "Joint Stiffness" },
//   { name: "Skin Discoloration" },
//   { name: "Confusion" },
//   { name: "Memory Problems" },
//   { name: "Difficulty Concentrating" },
//   { name: "Mood Swings" },
//   { name: "Hallucinations" },
//   { name: "Seizures" },
//   { name: "Tremors" },
//   { name: "Weakness" },
//   { name: "Blurred Vision" },
//   { name: "Dry Eyes" },
//   { name: "Chest Tightness" },
//   { name: "Abdominal Bloating" },
//   { name: "Constipation" },
//   { name: "Diarrhea with Blood" },
//   { name: "Blood in Stool" },
//   { name: "Hemorrhoids" },
//   { name: "Urinary Frequency" },
//   { name: "Painful Urination" },
//   { name: "Blood in Urine" },
//   { name: "Frequent Nighttime Urination" },
//   { name: "Changes in Taste or Smell" },
//   { name: "Loss of Smell or Taste" },
//   { name: "Fever" },
//   { name: "Headache" },
//   { name: "Cough" },
//   { name: "Sore Throat" },
//   { name: "Runny or Stuffy Nose" },
//   { name: "Shortness of Breath" },
//   { name: "Fatigue" },
//   { name: "Nausea" },
//   { name: "Vomiting" },
//   { name: "Diarrhea" },
//   { name: "Abdominal Pain" },
//   { name: "Chest Pain" },
//   { name: "Back Pain" },
//   { name: "Joint Pain" },
//   { name: "Muscle Pain" },
//   { name: "Swelling" },
//   { name: "Rash" },
//   { name: "Itching" },
//   { name: "Difficulty Swallowing" },
//   { name: "Dizziness" },
//   { name: "Fainting" },
//   { name: "Vision Changes" },
//   { name: "Hearing Loss" },
//   { name: "Bleeding or Bruising" },
//   { name: "Numbness or Tingling" },
//   { name: "Urinary Problems" },
//   { name: "Bowel Problems" },
//   { name: "Weight Loss" },
//   { name: "Weight Gain" },
//   { name: "Loss of Appetite" }
// ];
