const pres = {
  isPreHand: true,
  apointmentId: null,
  isHeader: true,
  patient: {
    patientName: '',
    patientAge: '',
    patientBloodGroup: '',
    patientProfileId: '',
    patientCode: '',
  },
  doctor: {
    doctorName: 'Asst. Prof. Dr. Bipul Kumar Das ',
    doctorProfileId: 40272,
    specializationName: '',
    doctorCode: 'SGD20241117135',
    degree: [
      {
        degreeName: 'MBBS',
        instituteName: 'Dhaka University',
        instituteCity: 'Dhaka,',
        instituteCountry: 'Bangladesh',
      },
      {
        degreeName: 'BCS (Health)',
        instituteName: 'Bangladesh Civil Service ',
        instituteCity: 'Dhaka,',
        instituteCountry: 'Bangladesh',
      },
      {
        degreeName: 'MS',
        instituteName: 'BSMMU-Bangabandhu Sheikh Mujib Medical University',
        instituteCity: 'Dhaka',
        instituteCountry: 'Bangladesh',
      },
    ],
    areaOfExperties: ' Orthopedic Trauma Surgeon & Orthopedic',
    qualification: 'MBBS,BCS (Health),MS',
    chamber: [],
    schedule: [],
    bmdc: 'A-53822',
  },
  chiefComplaints: [],
  history: [],
  examination: [
    {
      systolic: 12,
      diastolic: 80,
      pulse: 1,
      temperature: 5,
      weight: 5,
      heightFeet: 45,
      heightInches: 54,
    },
  ],
  diagnosis: [],
  medications: [],
  test: [],
  advice: [],
  followUp: '',
};
